#
# Configuration for Linux
#
# This makefile has been modified from Professor Shafae's FreeBSD configuration
# by Brian Mitzel for use in CPSC 486 Assignment 2 - Picking
#
# OPENGL_KIT_HOME must point to the root directory where the include and lib
# directory can be found for the project's dependencies.
#
OPENGL_KIT_HOME = /usr
CFLAGS += -g -DNDEBUG -Wall -pedantic -pipe -I ${OPENGL_KIT_HOME}/include
LDFLAGS += -g -Wall -pipe -L ${OPENGL_KIT_HOME}/lib
LLDLIBS += -lglut -lGLU -lGLEW -lGL
